In [1]:
import pandas as pd
import numpy as np

In [2]:
x = [[0.1,0.6],[0.15,0.71],[0.08,0.9],[0.16,0.85],[0.2,0.3],[0.25,0.5],[0.24,0.1],[0.3,0.2]]

In [5]:
centers = np.array([[0.1,0.6],[0.3,0.2]])
centers

array([[0.1, 0.6],
       [0.3, 0.2]])

In [8]:
from sklearn.cluster import KMeans
model = KMeans(n_clusters=2, init=centers,n_init=1)
model.fit(x)

KMeans(init=array([[0.1, 0.6],
       [0.3, 0.2]]), n_clusters=2, n_init=1)

In [9]:
model.labels_

array([0, 0, 0, 0, 1, 0, 1, 1])

In [10]:
model.labels_[5]

0

In [11]:
np.count_nonzero(model.labels_==1)

3

In [12]:
model.cluster_centers_

array([[0.148     , 0.712     ],
       [0.24666667, 0.2       ]])